# -*- coding: utf-8 -*-
"""Py_Assessment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XREuilmbqq70rBFvRjjxzwlLiHcfBXs_

**LAB 1**
"""

#1
length = float(input('Enter length: '))
width = float(input('Enter width: '))
area = length * width
print('Area of the rectangle:', area)

#2
weight = float(input('Enter weight in kilograms: '))
height = float(input('Enter height in meters: '))
bmi = weight / (height ** 2)
print('Your BMI is:', bmi)

#3
student_scores = {'Disha': 85,
                  'Saira': 90,
                  'Helen': 75,
                  'Priya': 67,
                  'Shane': 77,
                  'Manisha': 99,
                  'Neha': 87}
for name, score in student_scores.items():
    print(name, ':', score)

"""**LAB 2**"""

#4
age = int(input('Enter your age: '))
if age < 18:
    print('You are a minor.')
elif age >= 18 and age < 65:
    print('You are an adult.')
else:
    print('You are a senior.')

#5
for i in range(2, 51, 2):
    print(i)

#6
correctpw = 'password'
while True:
    password = input('Enter the password: ')
    if password == correctpw:
        print('The password is correct')
        break
    else:
        print('Incorrect password')

"""**LAB 3**"""

#7
def average(numbers):
    return sum(numbers)/len(numbers)
numbers = [55,86,93,57,98]
average = average(numbers)
print('Average:', average)

#8
def vowels(text):
    vowels = 'aeiouAEIOU'
    count = 0
    for n in text:
        if n in vowels:
            count += 1
    return count
text = 'Hello world'
print('Number of vowels:', vowels(text))

#9
from datetime import datetime
currentdatetime = datetime.now()
print('Current date and time:', currentdatetime)

"""**LAB 4**"""

#10
def addnums(num1, num2):
    try:
        return int(num1) + int(num2)
    except ValueError:
        return 'Error: Non-numeric input provided.'
result = addnums('5', 'abc')
print(result)

#11
while True:
    try:
        num = int(input('Enter an integer: '))
        break
    except ValueError:
        print('Invalid input. Enter an integer.')
print('You entered:', num)

#12
def divide(num1, num2):
    try:
        return num1 / num2
    except ZeroDivisionError:
        return 'Error: division by zero.'
result = divide(10, 0)
print(result)

"""**LAB 5**"""

#13
with open('python.txt', 'w') as file:
    file.write('Hello, Python! ')

#14
with open('python.txt', 'r') as file:
    content = file.read()
    print(content)

#15
with open('python.txt', 'a') as file:
    file.write('Hello World')

with open('python.txt', 'r') as file:
    content = file.read()
    print(content)